name: Publish models

on: [push]

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: write # Needed to push tags and create releases
      issues: write # Needed to post comments on issues/PRs
      pull-requests: write
      id-token: write # NPM's Provenance and OIDC features

    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # semantic-release needs to see your entire git history and all existing tags to determine the next version number.

      - uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: 'npm' # Speeds up "Install packages" step

      - name: Install packages
        run: npm ci

      - name: Security audit
        run: npm audit --audit-level=moderate --omit=dev

      - name: Format check
        run: npm run format

      - name: Lint check
        run: npm run lint

      - name: Spell check
        run: npm run spell -- --no-progress

      - name: Type check
        run: npm run types

      - name: Unit tests
        run: npm test

      - name: Build library
        run: npm run build

      - name: Release
        run: npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
